trigger: none

parameters:
  - name: environment
    displayName: Deployment Environment
    type: string
    default: dev
    values:
      - dev
      - prod

  - name: serviceConnection
    displayName: Azure Service Connection Name
    type: string

  - name: deployRG
    type: boolean
    default: false

  - name: logAnalyticsWorkspace
    type: boolean
    default: false

  - name: appInsights
    type: boolean
    default: false

  - name: appServicePlan
    type: boolean
    default: false

  - name: appService
    type: boolean
    default: false

  - name: keyVault
    type: boolean
    default: false

  - name: storageAccount
    type: boolean
    default: false

    
# ---------------------------------------------------
# GLOBAL VARIABLE IMPORT (READS JSON ONCE)
# ---------------------------------------------------
variables:
  - template: parameters/${{ parameters.environment }}/main.parameters.yml
# ---------------------------------------------------



pool:
  vmImage: ubuntu-latest


# ---------------------------------------------------
# STAGES
# ---------------------------------------------------
stages:
  - stage: DeployInfrastructure
    displayName: Deploy Azure Infrastructure
    jobs:
      - job: Deploy
        displayName: Deploy Azure Resources
        steps:
          # -------------------------------------------------------
          # DEBUG VARIABLES
          # -------------------------------------------------------
          - script: |
              echo Subscription ID: $(subscriptionId)
              echo Service Connection: $(serviceConnectionName)
              echo Location: $(location)
            displayName: "Check variables"

          # -------------------------------------------------------
          # RESOURCE GROUP DEPLOYMENT
          # -------------------------------------------------------
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy Resource Group
            condition: |
              and(succeeded(), eq('${{ parameters.deployRG }}', 'true'))
            inputs:
              deploymentScope: 'Subscription'
              azureResourceManagerConnection: ${{ parameters.serviceConnection }}
              subscriptionId: $(subscriptionId)
              location: $(location)
              templateLocation: 'Linked artifact'
              csmFile: 'subscription-level/rg.bicep'
              csmParametersFile: 'azure-pipelines/parameters/${{ parameters.environment }}/rg.parameters.json'
              deploymentMode: Incremental
              deploymentName: rg-${{ parameters.environment }}
          # -------------------------------------------------------
          # Log Analytics Workspace DEPLOYMENT
          # -------------------------------------------------------
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy Log Analytics Workspace
            condition: |
              and(succeeded(), eq('${{ parameters.logAnalyticsWorkspace }}', 'true'))
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: ${{ parameters.serviceConnection }}
              subscriptionId: $(subscriptionId)
              location: $(location)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(rgName)
              templateLocation: 'Linked artifact'
              csmFile: 'resource-group-level/modules/logAnalytics.bicep'
              csmParametersFile: 'azure-pipelines/parameters/${{ parameters.environment }}/logAnalytics.parameters.json'
              deploymentMode: Incremental
              deploymentName: loganalytics-${{ parameters.environment }}

             # -------------------------------------------------------
          # AppInsights DEPLOYMENT
          # -------------------------------------------------------
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy AppInsights
            condition: |
              and(succeeded(), eq('${{ parameters.appInsights }}', 'true'))
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: ${{ parameters.serviceConnection }}
              subscriptionId: $(subscriptionId)
              location: $(location)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(rgName)
              templateLocation: 'Linked artifact'
              csmFile: 'resource-group-level/modules/appInsights.bicep'
              csmParametersFile: 'azure-pipelines/parameters/${{ parameters.environment }}/appInsights.parameters.json'
              deploymentMode: Incremental
              deploymentName: appInsights-${{ parameters.environment }}

             # -------------------------------------------------------
          # Appservice plan DEPLOYMENT
          # -------------------------------------------------------
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy appServicePlan
            condition: |
              and(succeeded(), eq('${{ parameters.appServicePlan }}', 'true'))
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: ${{ parameters.serviceConnection }}
              subscriptionId: $(subscriptionId)
              location: $(location)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(rgName)
              templateLocation: 'Linked artifact'
              csmFile: 'resource-group-level/modules/appServicePlan.bicep'
              csmParametersFile: 'azure-pipelines/parameters/${{ parameters.environment }}/appServicePlan.parameters.json'
              deploymentMode: Incremental
              deploymentName: appServicePlan-${{ parameters.environment }}

             # -------------------------------------------------------
          # appService DEPLOYMENT
          # -------------------------------------------------------
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy appService 
            condition: |
              and(succeeded(), eq('${{ parameters.appService }}', 'true'))
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: ${{ parameters.serviceConnection }}
              subscriptionId: $(subscriptionId)
              location: $(location)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(rgName)
              templateLocation: 'Linked artifact'
              csmFile: 'resource-group-level/modules/appService.bicep'
              csmParametersFile: 'azure-pipelines/parameters/${{ parameters.environment }}/appService.parameters.json'
              deploymentMode: Incremental
              deploymentName: appService-${{ parameters.environment }}

             # -------------------------------------------------------
          # Keyvault  DEPLOYMENT
          # -------------------------------------------------------
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy keyVault 
            condition: |
              and(succeeded(), eq('${{ parameters.keyVault }}', 'true'))
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: ${{ parameters.serviceConnection }}
              subscriptionId: $(subscriptionId)
              location: $(location)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(rgName)
              templateLocation: 'Linked artifact'
              csmFile: 'resource-group-level/modules/keyVault.bicep'
              csmParametersFile: 'azure-pipelines/parameters/${{ parameters.environment }}/keyVault.parameters.json'
              deploymentMode: Incremental
              deploymentName: keyVault-${{ parameters.environment }}

             # -------------------------------------------------------
          # storageAccount DEPLOYMENT
          # -------------------------------------------------------
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy storageAccount
            condition: |
              and(succeeded(), eq('${{ parameters.storageAccount }}', 'true'))
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: ${{ parameters.serviceConnection }}
              subscriptionId: $(subscriptionId)
              location: $(location)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(rgName)
              templateLocation: 'Linked artifact'
              csmFile: 'resource-group-level/modules/storageAccount.bicep'
              csmParametersFile: 'azure-pipelines/parameters/${{ parameters.environment }}/storageAccount.parameters.json'
              deploymentMode: Incremental
              deploymentName: storageAccount-${{ parameters.environment }}

        
        
